version: '3'
services:
  oss-argus-jenkins:
    image: oss-argus-jenkins
    env_file:
      - /var/tmp/.jenkins.env
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: